on:
  push:
  pull_request:
    branches: [master]

permissions:
  contents: write
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run -e nodemcuv2
    - name: Archive Firmware Files
      uses: actions/upload-artifact@v3
      with: 
        name: esp8266-firmware
        path: ".pio/build/nodemcuv2/firmware.bin"
        
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Firmware Files
      uses: actions/download-artifact@v3
    - name: Release Firmware
      uses: ncipollo/release-action@v1
      #if: startsWith(github.ref, 'refs/tags/')
      with:
        artifacts: esp8266-firmware.bin
        generateReleaseNotes: true
        allowUpdates: true
        #token: ${{ secrets.GITHUB_TOKEN }}
